<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="background.jpg.jpg" />
    <None Remove="Images\background.jpg.jpg" />
    <None Remove="Снимок экрана 2026-06-16 185350.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\background.jpg.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="background.jpg.jpg" />
    <Resource Include="Снимок экрана 2026-06-16 185350.png" />
  </ItemGroup>

</Project>
